In [2]:
import pandas as pd
from nba_api.stats.endpoints import leaguedashlineups
import time

In [1]:
import nba_api
print(nba_api.__version__)

# Check what parameters LeagueDashLineups actually accepts
from nba_api.stats.endpoints import leaguedashlineups
help(leaguedashlineups.LeagueDashLineups.__init__)

1.11.4
Help on function __init__ in module nba_api.stats.endpoints.leaguedashlineups:

__init__(
    self,
    group_quantity='5',
    last_n_games='0',
    measure_type_detailed_defense='Base',
    month='0',
    opponent_team_id=0,
    pace_adjust='N',
    per_mode_detailed='Totals',
    period='0',
    plus_minus='N',
    rank='N',
    season='2025-26',
    season_type_all_star='Regular Season',
    conference_nullable='',
    date_from_nullable='',
    date_to_nullable='',
    division_simple_nullable='',
    game_segment_nullable='',
    league_id_nullable='00',
    location_nullable='',
    outcome_nullable='',
    po_round_nullable='',
    season_segment_nullable='',
    shot_clock_range_nullable='',
    team_id_nullable='',
    vs_conference_nullable='',
    vs_division_nullable='',
    proxy=None,
    headers=None,
    timeout=30,
    get_request=True
)
    Initialize self.  See help(type(self)) for accurate signature.

In [ ]:
import inspect
sig = inspect.signature(leaguedashlineups.LeagueDashLineups.__init__)
print(list(sig.parameters.keys()))

['self', 'group_quantity', 'last_n_games', 'measure_type_detailed_defense', 'month', 'opponent_team_id', 'pace_adjust', 'per_mode_detailed', 'period', 'plus_minus', 'rank', 'season', 'season_type_all_star', 'conference_nullable', 'date_from_nullable', 'date_to_nullable', 'division_simple_nullable', 'game_segment_nullable', 'league_id_nullable', 'location_nullable', 'outcome_nullable', 'po_round_nullable', 'season_segment_nullable', 'shot_clock_range_nullable', 'team_id_nullable', 'vs_conference_nullable', 'vs_division_nullable', 'proxy', 'headers', 'timeout', 'get_request']

In [ ]:
# test connection on a sample

def test_storm_lineups():
    print("Fetching 2024 Storm lineup data...")
    
    result = leaguedashlineups.LeagueDashLineups(
        season='2024',
        season_type_all_star='Regular Season',
        league_id_nullable='10',           
        measure_type_detailed_defense='Base', 
        per_mode_detailed='Per100Possessions',
        team_id_nullable='1611661317'
    ).get_data_frames()[0]
    
    print(f"Success! Shape: {result.shape}")
    print(f"\nColumns:\n{result.columns.tolist()}")
    print(f"\nFirst row:\n{result.iloc[0]}")
    
    return result

df = test_storm_lineups()

Fetching 2024 Storm lineup data...
Success! Shape: (217, 58)

Columns:
['GROUP_SET', 'GROUP_ID', 'GROUP_NAME', 'TEAM_ID', 'TEAM_ABBREVIATION', 'GP', 'W', 'L', 'W_PCT', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD', 'PTS', 'PLUS_MINUS', 'GP_RANK', 'W_RANK', 'L_RANK', 'W_PCT_RANK', 'MIN_RANK', 'FGM_RANK', 'FGA_RANK', 'FG_PCT_RANK', 'FG3M_RANK', 'FG3A_RANK', 'FG3_PCT_RANK', 'FTM_RANK', 'FTA_RANK', 'FT_PCT_RANK', 'OREB_RANK', 'DREB_RANK', 'REB_RANK', 'AST_RANK', 'TOV_RANK', 'STL_RANK', 'BLK_RANK', 'BLKA_RANK', 'PF_RANK', 'PFD_RANK', 'PTS_RANK', 'PLUS_MINUS_RANK', 'SUM_TIME_PLAYED']

First row:
GROUP_SET                                                      Lineups
GROUP_ID                       -100940-204333-1627674-1628881-1629482-
GROUP_NAME           D. Taurasi - N. Cloud - K. Copper - M. Billing...
TEAM_ID                                                     1611661317
TEAM_ABBREVIATION                                                  PHO
GP                                                                   2
W                                                                    2
L                                                                    0
W_PCT                                                              1.0
MIN                                                              106.5
FGM                                                              100.0
FGA                                                              100.0
FG_PCT                                                             1.0
FG3M                                                             100.0
FG3A                                                             100.0
FG3_PCT                                                            1.0
FTM                                                                0.0
FTA                                                                0.0
FT_PCT                                                             0.0
OREB                                                               0.0
DREB                                                               0.0
REB                                                                0.0
AST                                                              100.0
TOV                                                                0.0
STL                                                                0.0
BLK                                                                0.0
BLKA                                                               0.0
PF                                                               300.0
PFD                                                                0.0
PTS                                                              300.0
PLUS_MINUS                                                      -100.0
GP_RANK                                                             57
W_RANK                                                              28
L_RANK                                                               1
W_PCT_RANK                                                           1
MIN_RANK                                                             1
FGM_RANK                                                             1
FGA_RANK                                                            19
FG_PCT_RANK                                                          1
FG3M_RANK                                                            1
FG3A_RANK                                                            2
FG3_PCT_RANK                                                         1
FTM_RANK                                                           109
FTA_RANK                                                           114
FT_PCT_RANK                                                        109
OREB_RANK                                                           93
DREB_RANK                                                          162
REB_RANK                                                           177
AST_RANK                                                             1
TOV_RANK                                                             1
STL_RANK                                                            86
BLK_RANK                                                            73
BLKA_RANK                                                            1
PF_RANK                                                            217
PFD_RANK                                                           145
PTS_RANK                                                             1
PLUS_MINUS_RANK                                                    174
SUM_TIME_PLAYED                                                   3195
Name: 0, dtype: object

In [5]:
# find the storm id
# Pull all WNBA lineups without filtering by team
result = leaguedashlineups.LeagueDashLineups(
    season='2024',
    season_type_all_star='Regular Season',
    league_id_nullable='10',
    measure_type_detailed_defense='Base',
    per_mode_detailed='Per100Possessions',
).get_data_frames()[0]

# See all teams and their IDs
print(result[['TEAM_ID', 'TEAM_ABBREVIATION']].drop_duplicates().sort_values('TEAM_ABBREVIATION'))

       TEAM_ID TEAM_ABBREVIATION
6   1611661330               ATL
10  1611661329               CHI
41  1611661323               CON
2   1611661321               DAL
23  1611661325               IND
17  1611661320               LAS
7   1611661319               LVA
8   1611661324               MIN
0   1611661313               NYL
1   1611661317               PHO
9   1611661328               SEA
18  1611661322               WAS

In [8]:
# try it with the seattle id

def test_storm_lineups():
    print("Fetching 2024 Storm lineup data...")
    
    result = leaguedashlineups.LeagueDashLineups(
        season='2024',
        season_type_all_star='Regular Season',
        league_id_nullable='10',
        measure_type_detailed_defense='Base',
        per_mode_detailed='Per100Possessions',
        team_id_nullable='1611661328'
    ).get_data_frames()[0]
    
    print(f"Success! Shape: {result.shape}")
    print(f"\nFirst 5 lineups:\n{result[['GROUP_NAME', 'MIN', 'PLUS_MINUS']].head()}")
    
    return result

df = test_storm_lineups()

Fetching 2024 Storm lineup data...
Success! Shape: (134, 58)

First 5 lineups:
                                          GROUP_NAME   MIN  PLUS_MINUS
0  S. Diggins-Smith - S. Whitcomb - V. Vivians - ...  91.7       200.0
1  J. Loyd - S. Whitcomb - V. Vivians - E. Magbeg...  88.3       100.0
2  S. Whitcomb - K. Williams - J. Horston - D. Fa...  65.3       120.0
3  S. Whitcomb - V. Vivians - G. Williams - J. Ho...  61.7      -200.0
4  J. Loyd - M. Russell - E. Magbegor - K. Willia...  58.8        40.0

In [ ]:
# how far back does the data go?
STORM_ID = '1611661328'

def check_season(season):
    try:
        df = leaguedashlineups.LeagueDashLineups(
            season=season,
            season_type_all_star='Regular Season',
            league_id_nullable='10',
            measure_type_detailed_defense='Base',
            per_mode_detailed='Per100Possessions',
            team_id_nullable=STORM_ID
        ).get_data_frames()[0]
        print(f"{season}: {len(df)} lineups returned")
        time.sleep(5)
    except Exception as e:
        print(f"{season}: FAILED — {e}")

# Spot check a spread of years
for season in ['2024', '2020']:
    check_season(season)

2024: 134 lineups returned
2020: FAILED — Expecting value: line 1 column 1 (char 0)

In [ ]:
# 2021 might be first year. investigate

def check_season_verbose(season):
    try:
        endpoint = leaguedashlineups.LeagueDashLineups(
            season=season,
            season_type_all_star='Regular Season',
            league_id_nullable='10',
            measure_type_detailed_defense='Base',
            per_mode_detailed='Per100Possessions',
            team_id_nullable=STORM_ID
        )
        df = endpoint.get_data_frames()[0]
        print(f"{season}: {len(df)} lineups returned")
        time.sleep(1)
    except Exception as e:
        print(f"{season}: FAILED — {e}")

# Binary search approach — start wide then narrow
for season in ['1997', '1998', '1999', '2000', '2001', '2020']:
    check_season_verbose(season)

# data starts in 2000

1997: 0 lineups returned
1998: 0 lineups returned
1999: 0 lineups returned
2000: 295 lineups returned
2001: 190 lineups returned
2020: 125 lineups returned

In [21]:
import os
print(os.getcwd())

c:\Users\casey\Documents\GitHub\wnba\notebooks

In [22]:
# the Storm began play in 2000, so that checks out
# lets pull all Storm lineup data history

STORM_ID = '1611661328'

def get_storm_lineups(season, measure_type='Base'):
    try:
        df = leaguedashlineups.LeagueDashLineups(
            season=season,
            season_type_all_star='Regular Season',
            league_id_nullable='10',
            measure_type_detailed_defense=measure_type,
            per_mode_detailed='Per100Possessions',
            team_id_nullable=STORM_ID
        ).get_data_frames()[0]
        
        if len(df) == 0:
            print(f"  {season} {measure_type}: empty")
            return None
            
        df['SEASON'] = season
        df['MEASURE_TYPE'] = measure_type
        print(f"  {season} {measure_type}: {len(df)} lineups")
        time.sleep(10)  # conservative sleep
        return df
        
    except Exception as e:
        print(f"  {season} {measure_type}: FAILED — {e}")
        time.sleep(30)  # longer sleep on failure
        return None

seasons = [str(y) for y in range(2000, 2025)]

base_frames = []
adv_frames = []

for season in seasons:
    print(f"Fetching {season}...")
    
    base = get_storm_lineups(season, 'Base')
    if base is not None:
        base_frames.append(base)
    
    adv = get_storm_lineups(season, 'Advanced')
    if adv is not None:
        adv_frames.append(adv)

# Only concat non-empty results
if base_frames:
    base_df = pd.concat(base_frames, ignore_index=True)
    base_df.to_csv('../data/raw/storm_lineups_base.csv', index=False)
    print(f"\nBase shape: {base_df.shape}")
    print(f"Seasons with data: {sorted(base_df['SEASON'].unique())}")

if adv_frames:
    adv_df = pd.concat(adv_frames, ignore_index=True)
    adv_df.to_csv('../data/raw/storm_lineups_advanced.csv', index=False)
    print(f"Advanced shape: {adv_df.shape}")

Fetching 2000...
  2000 Base: 295 lineups
  2000 Advanced: 295 lineups
Fetching 2001...
  2001 Base: 190 lineups
  2001 Advanced: 190 lineups
Fetching 2002...
  2002 Base: 202 lineups
  2002 Advanced: 202 lineups
Fetching 2003...
  2003 Base: 178 lineups
  2003 Advanced: 178 lineups
Fetching 2004...
  2004 Base: 128 lineups
  2004 Advanced: 128 lineups
Fetching 2005...
  2005 Base: 144 lineups
  2005 Advanced: 144 lineups
Fetching 2006...
  2006 Base: 214 lineups
  2006 Advanced: 214 lineups
Fetching 2007...
  2007 Base: 164 lineups
  2007 Advanced: 164 lineups
Fetching 2008...
  2008 Base: 217 lineups
  2008 Advanced: 217 lineups
Fetching 2009...
  2009 Base: 157 lineups
  2009 Advanced: 157 lineups
Fetching 2010...
  2010 Base: 122 lineups
  2010 Advanced: 122 lineups
Fetching 2011...
  2011 Base: 110 lineups
  2011 Advanced: 110 lineups
Fetching 2012...
  2012 Base: 167 lineups
  2012 Advanced: 167 lineups
Fetching 2013...
  2013 Base: 118 lineups
  2013 Advanced: 118 lineups
Fetching 2014...
  2014 Base: 188 lineups
  2014 Advanced: 188 lineups
Fetching 2015...
  2015 Base: 179 lineups
  2015 Advanced: 179 lineups
Fetching 2016...
  2016 Base: 138 lineups
  2016 Advanced: 138 lineups
Fetching 2017...
  2017 Base: 129 lineups
  2017 Advanced: 129 lineups
Fetching 2018...
  2018 Base: 150 lineups
  2018 Advanced: 150 lineups
Fetching 2019...
  2019 Base: 132 lineups
  2019 Advanced: FAILED — HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
Fetching 2020...
  2020 Base: FAILED — HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
  2020 Advanced: 125 lineups
Fetching 2021...
  2021 Base: 159 lineups
  2021 Advanced: FAILED — Expecting value: line 1 column 1 (char 0)
Fetching 2022...
  2022 Base: 148 lineups
  2022 Advanced: 148 lineups
Fetching 2023...
  2023 Base: 212 lineups
  2023 Advanced: 212 lineups
Fetching 2024...
  2024 Base: 134 lineups
  2024 Advanced: 134 lineups

Base shape: (3975, 60)
Seasons with data: ['2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2021', '2022', '2023', '2024']
Advanced shape: (3809, 52)

In [23]:
# we had a few pulls fail: 2019 advanced, 2020 base, and 2021 advanced.
# double check that is all we're missing

base_df = pd.read_csv('../data/raw/storm_lineups_base.csv')
adv_df = pd.read_csv('../data/raw/storm_lineups_advanced.csv')

print("Base seasons:", sorted(base_df['SEASON'].unique()))
print("Advanced seasons:", sorted(adv_df['SEASON'].unique()))

Base seasons: [np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)]
Advanced seasons: [np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2020), np.int64(2022), np.int64(2023), np.int64(2024)]

In [25]:
# try again to get the missing ones
def get_storm_lineups(season, measure_type='Base'):
    try:
        df = leaguedashlineups.LeagueDashLineups(
            season=season,
            season_type_all_star='Regular Season',
            league_id_nullable='10',
            measure_type_detailed_defense=measure_type,
            per_mode_detailed='Per100Possessions',
            team_id_nullable=STORM_ID
        ).get_data_frames()[0]
        
        if len(df) == 0:
            print(f"  {season} {measure_type}: empty")
            return None
            
        df['SEASON'] = season
        df['MEASURE_TYPE'] = measure_type
        print(f"  {season} {measure_type}: {len(df)} lineups")
        time.sleep(3)
        return df
        
    except Exception as e:
        print(f"  {season} {measure_type}: FAILED — {e}")
        time.sleep(5)
        return None

# Only the missing ones
missing = {
    'Base': ['2020'],
    'Advanced': ['2019', '2021']
}

for measure_type, seasons in missing.items():
    filename = f'../data/raw/storm_lineups_{measure_type.lower()}.csv'
    existing = pd.read_csv(filename)
    
    new_frames = []
    for season in seasons:
        print(f"Fetching {season} {measure_type}...")
        df = get_storm_lineups(season, measure_type)
        if df is not None:
            new_frames.append(df)
    
    if new_frames:
        combined = pd.concat([existing] + new_frames, ignore_index=True)
        combined['SEASON'] = combined['SEASON'].astype(int)
        combined = combined.sort_values('SEASON').reset_index(drop=True)
        combined.to_csv(filename, index=False)
        print(f"Updated {filename}: {combined['SEASON'].unique()}")

Fetching 2020 Base...
  2020 Base: 125 lineups
Updated ../data/raw/storm_lineups_base.csv: [2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013
 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024]
Fetching 2019 Advanced...
  2019 Advanced: FAILED — Expecting value: line 1 column 1 (char 0)
Fetching 2021 Advanced...
  2021 Advanced: FAILED — Expecting value: line 1 column 1 (char 0)

In [26]:
# that got base added and complete, but still missing advanced in 2019 and 2021
adv_df = pd.read_csv('../data/raw/storm_lineups_advanced.csv')
print("Advanced seasons:", sorted(adv_df['SEASON'].unique()))

Advanced seasons: [np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2020), np.int64(2022), np.int64(2023), np.int64(2024)]

In [28]:
# is this just a one off that those are failing?
def check_season_verbose(season, measure_type):
    try:
        endpoint = leaguedashlineups.LeagueDashLineups(
            season=season,
            season_type_all_star='Regular Season',
            league_id_nullable='10',
            measure_type_detailed_defense=measure_type,
            per_mode_detailed='Per100Possessions',
            team_id_nullable=STORM_ID
        )
        raw = endpoint.get_response()
        # Look further in and specifically at the rowSet
        print(f"{season} {measure_type}:")
        print(f"  Total response length: {len(str(raw))}")
        print(f"  End of response: {str(raw)[-300:]}")
        time.sleep(1)
    except Exception as e:
        print(f"{season} {measure_type}: FAILED — {e}")

check_season_verbose('2019', 'Advanced')
check_season_verbose('2021', 'Advanced')
check_season_verbose('2022', 'Advanced')

2019 Advanced:
  Total response length: 42751
  End of response: -201919-203827-204319-1628920-1629500-","S. Zellous - N. Howard - J. Loyd - M. Russell - A. Howard",1611661328,"SEA",1,0,1,0.0,0.0,0.0,0.0,227.3,100.0,-227.3,-100.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,94.3,130.91,109.09,1,1.5,84,94,27,94,126,110,76,117,95,75,95,86,111,118,132,105,110,16,10,1100]]}]}
2021 Advanced:
  Total response length: 50996
  End of response: ineups","-100720-204319-1627668-1629478-1629568-","S. Bird - J. Loyd - B. Stewart - K. Samuelson - K. Burke",1611661328,"SEA",1,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,137.1,137.14,114.29,1,0.5,81,111,58,111,155,136,1,73,111,82,111,97,135,140,1,129,136,13,74,1050]]}]}
2022 Advanced:
  Total response length: 47121
  End of response: ,["Lineups","-202250-203855-204319-1627668-1628931-","T. Charles - S. Talbot - J. Loyd - B. Stewart - G. Williams",1611661328,"SEA",1,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,400.0,333.33,0,0.0,65,105,61,105,147,116,1,53,98,71,98,79,119,126,1,111,116,2,107,180]]}]}

In [29]:
# lets try again
missing_adv = ['2019', '2021']
adv_existing = pd.read_csv('../data/raw/storm_lineups_advanced.csv')
new_frames = []

for season in missing_adv:
    print(f"Fetching {season} Advanced...")
    df = get_storm_lineups(season, 'Advanced')
    if df is not None:
        new_frames.append(df)

if new_frames:
    combined = pd.concat([adv_existing] + new_frames, ignore_index=True)
    combined['SEASON'] = combined['SEASON'].astype(int)
    combined = combined.sort_values('SEASON').reset_index(drop=True)
    combined.to_csv('../data/raw/storm_lineups_advanced.csv', index=False)
    print(f"Updated advanced seasons: {sorted(combined['SEASON'].unique())}")
else:
    print("Still failing")

Fetching 2019 Advanced...
  2019 Advanced: 132 lineups
Fetching 2021 Advanced...
  2021 Advanced: 159 lineups
Updated advanced seasons: [np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)]

In [3]:
# we have them all now i believe
base_df = pd.read_csv('../data/raw/storm_lineups_base.csv')
adv_df = pd.read_csv('../data/raw/storm_lineups_advanced.csv')

print("Base seasons:", sorted(base_df['SEASON'].unique()))
print("Base shape:", base_df.shape)
print("\nAdvanced seasons:", sorted(adv_df['SEASON'].unique()))
print("Advanced shape:", adv_df.shape)

Base seasons: [np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)]
Base shape: (4100, 60)

Advanced seasons: [np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)]
Advanced shape: (4100, 52)

In [4]:
base_df.head()

,GROUP_SET,GROUP_ID,GROUP_NAME,TEAM_ID,TEAM_ABBREVIATION,GP,W,L,W_PCT,MIN,...,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,SUM_TIME_PLAYED,SEASON,MEASURE_TYPE
0,Lineups,-100111-100336-100538-100542-100544-,S. Edwards - S. Henning - K. Hibbert - C. Samp...,1611661328,SEA,1,0,1,0.0,83.3,...,121,62,1,1,3,224,89,5000,2000,Base
1,Lineups,-100111-100336-100375-100441-100503-,S. Edwards - S. Henning - E. Campbell - A. Ayc...,1611661328,SEA,1,0,1,0.0,83.3,...,121,62,1,270,59,224,275,5000,2000,Base
2,Lineups,-100230-100336-100538-100542-100544-,Q. Barnes - S. Henning - K. Hibbert - C. Samps...,1611661328,SEA,1,0,1,0.0,83.3,...,121,62,294,270,59,224,89,2500,2000,Base
3,Lineups,-100088-100470-100538-100543-100544-,M. Edwards - S. Lovelace - K. Hibbert - R. Thr...,1611661328,SEA,1,0,1,0.0,83.3,...,121,62,1,292,59,4,89,2500,2000,Base
4,Lineups,-100088-100179-100503-100543-100544-,M. Edwards - C. Smith - A. Garner - R. Threatt...,1611661328,SEA,2,0,2,0.0,86.1,...,13,62,1,172,5,31,89,7750,2000,Base

In [5]:
adv_df.head()

,GROUP_SET,GROUP_ID,GROUP_NAME,TEAM_ID,TEAM_ABBREVIATION,GP,W,L,W_PCT,MIN,...,DREB_PCT_RANK,REB_PCT_RANK,TM_TOV_PCT_RANK,EFG_PCT_RANK,TS_PCT_RANK,PACE_RANK,PIE_RANK,SUM_TIME_PLAYED,SEASON,MEASURE_TYPE
0,Lineups,-100111-100230-100336-100541-100543-,S. Edwards - Q. Barnes - S. Henning - J. Redd ...,1611661328,SEA,6,3,3,0.500,18.0,...,14,8,202,105,86,169,108,53100,2000,Advanced
1,Lineups,-100111-100230-100336-100375-100503-,S. Edwards - Q. Barnes - S. Henning - E. Campb...,1611661328,SEA,2,0,2,0.000,18.0,...,30,8,112,171,199,193,173,54600,2000,Advanced
2,Lineups,-100230-100336-100375-100538-100544-,Q. Barnes - S. Henning - E. Campbell - K. Hibb...,1611661328,SEA,4,0,4,0.000,19.0,...,30,8,147,191,196,208,218,56700,2000,Advanced
3,Lineups,-100179-100230-100503-100541-100543-,C. Smith - Q. Barnes - A. Garner - J. Redd - R...,1611661328,SEA,3,0,3,0.000,19.0,...,4,8,227,61,72,244,95,57850,2000,Advanced
4,Lineups,-100111-100179-100336-100375-100544-,S. Edwards - C. Smith - S. Henning - E. Campbe...,1611661328,SEA,6,1,5,0.167,20.0,...,17,5,112,126,142,113,138,59770,2000,Advanced